development:
  adapter: postgresql
  encoding: unicode
  database: hacker_development
  host: localhost
  pool: 5
  username: hacker
  password: root

test: 
  adapter: postgresql
  encoding: unicode
  database: hacker_test
  host: localhost
  pool: 5
  username: hacker
  password: root

production:
  adapter: postgresql
  encoding: unicode
  database: hacker_production
  host: localhost
  pool: 5
  username: hacker 
  password: root
